name: Build

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      release:
        type: boolean
        required: false
        default: false

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Setup SCons
        shell: bash
        run: |
          python -c 'import sys; print(sys.version)'
          python -m pip install scons==4.4.0
          scons --version

      - name: Build extension (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          scons platform=linux arch=x86_64 single_source=true

      - name: Build extension (Windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          scons platform=windows arch=x86_64 single_source=true

      - name: Create archive (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          cd bin/
          zip -q -r ../godot-python-linux-x86_64.zip *
          cd ../

      - name: Upload artifacts (Linux)
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v3
        with:
          name: godot-python-linux-x86_64
          path: godot-python*.zip
          retention-days: 30

      - name: Upload artifacts (Windows)
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v3
        with:
          name: godot-python-windows-x86_64
          path: |
            bin/**/*
            !bin/**/*.lib
            !bin/**/*.exp
          retention-days: 30

      - name: Release artifact
        if: ${{ inputs.release }}
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            echo "Releasing artifact for linux"
          elif [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            echo "Releasing artifact for windows"
